name: Build Release

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: ~/.dotnet
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          
      - name: Set up variables
        id: vars
        run: |
          # Extract package version from project
          version=$(grep -oP '<Version>\K[^<]+' RepoXR.csproj)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore NuGet packages
        run: dotnet restore
        
      - name: Build NuGet package
        run: dotnet pack -p:Version='1.0.2' -c Release
          
      - name: Build app
        run: dotnet build -c Release
          
      - name: Prepare and bundle package
        run: |
          # Set up template
          mkdir package
          git --work-tree=./package checkout origin/thunderstore ./
          
          # Copy and sign release binaries
          cp bin/Release/netstandard2.1/RepoXR.dll ./package/BepInEx/plugins/RepoXR/
          cp bin/Release/netstandard2.1/RepoXR.Preload.dll ./package/BepInEx/patchers/RepoXR/
          
          # Move assets
          mv ./package/repoxrassets ./package/BepInEx/plugins/RepoXR/repoxrassets
          
          # Copy docs and license
          cp CHANGELOG.md ./package/CHANGELOG.md
          cp LICENSE ./package/LICENSE
          
          # Update Thunderstore manifest
          jq '.version_number = "1.0.2"' ./package/manifest.json > ./package/manifest_new.json
          mv ./package/manifest_new.json ./package/manifest.json
          
      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: RepoXR-1.0.2
          path: ./package
